// frontend/src/components/Card/Recent.jsx
import { memo } from "react"
import { PropTypes } from "prop-types"
import { motion } from "framer-motion"
import { Link } from "react-router-dom"
import { getQueryParams, getDate } from "/src/services/untils"

const MAX_TITLE_SIZE = 25

const Recent = ({ data = {} }) => {
  const id = data.media.id
  const name =
    data.media.title.romaji ||
    data.media.title.english ||
    data.media.title.userPreferred ||
    data.media.title.native
  let title =
    data.media.title.userPreferred ||
    data.media.title.english ||
    data.media.title.romaji ||
    data.media.title.native
  if (title.length > MAX_TITLE_SIZE) {
    title = title.slice(0, MAX_TITLE_SIZE - 3) + '...'
  }
  const episode = data.episode
  const backgound = data.media.coverImage.extraLarge
  const format = data.media.format.replaceAll('_', ' ')
  const duration = (data.media.duration || 23) + ':00'
  const date = getDate(data.airingAt)

  return (
    <motion.div
      className="cursor-pointer hidden-recent-card h-full lg:w-1/4 md:w-1/3 sm:w-1/3 w-1/2 p-2"
      whileHover={{ scale: 1.03 }}
      whileTap={{ scale: 0.97 }}
    >
      <Link
        to={{
          pathname: '/watch',
          search: getQueryParams({ id, name, episode })
        }}
      >
        <div className="p-1 glass glass-hard w-full h-full">
          <div
            className="background aspect-[7/5] md:aspect-[8/5] lg:aspect-[9/5] relative p-2 rounded-lg"
            style={{
              backgroundImage: `url(${backgound})`,
            }}
          >
            <div
              className="rounded-sm bg-[#5de4b5] absolute top-2 left-2 bg-opacity-80 px-2 text-[12px] md:text-[15px] font-[550]">
              {format}</div>
            <div
              className="rounded-sm absolute bottom-2 right-2 bg-black bg-opacity-60 text-slate-200 px-2 py-[2px] text-[12px] md:text-[15px] font-[550]">
              {duration}</div>
          </div>
          <h1 className="text-[11px] md:text-[12px] pt-2 flex justify-between text-gray-100">
            <span>Episode:</span>
            <span>{episode}</span>
          </h1>
          <h1 className="text-[11px] md:text-[12px] pt-0 flex justify-between text-gray-100">
            <span>Aired on:</span>
            <span>{date}</span>
          </h1>
          <h1 className="text-[11px] md:text-sm pt-1 font-normal text-sgreen">
            {title}
          </h1>
        </div>
      </Link>
    </motion.div>
  )
}

Recent.propTypes = {
  data: PropTypes.any,
}

const MemoRecent = memo(Recent)

export default MemoRecent

// frontend/src/app/pages/recent/recent.component.ts
import { Component } from '@angular/core'
import { SharedviewService } from '../../services/sharedview/sharedview.service'
import { AnilistService } from 'src/app/services/anilist/anilist.service'

@Component({
	selector: 'app-recent',
	templateUrl: './recent.component.html',
	styleUrls: ['./recent.component.css']
})
export class RecentComponent {

	constructor(private sharedView: SharedviewService) {
		this.date = (x: number) => {
			let p: any = new Date(x * 1000)
			let dateExtention = 'th', date = p.getDate()
			if (date < 11 || 13 < date) {
				if (date % 10 == 1) {
					dateExtention = 'st'
				} else if (date % 10 == 2) {
					dateExtention = 'nd'
				} else if (date % 10 == 3) {
					dateExtention = 'rd'
				}
			}
			return date + dateExtention + ' ' + p.toString().slice(4, 7) + ' ' + p.toString().slice(16, 21)
		}
		this.currentPage = 1
		this.dataMethods = AnilistService.fetcher()
	}

	loading: any = {
		recent: true,
	}
	dataMethods: any = {}
	date: any = null
	recentData: any = []
	currentPage: number = 0

	variables: any = {
		recent: {
			page: 1,
			perPage: 24,
		},
	}

	setPageData: any = {
		recent: (data: any) => {
			const addAnimation = () => {
				const observerRecent = new IntersectionObserver(entries => {
					entries.forEach(entry => {
						if (entry.isIntersecting) {
							const delay = entry.target.getAttribute('delay')
							setTimeout(() => {
								entry.target.classList.add('show-recent-card')
							}, parseInt(delay || '0'))
						} else {
							entry.target.classList.remove('show-recent-card')
						}
					})
				})
				const hiddenElements = document.querySelectorAll('.hidden-recent-card')
				hiddenElements.forEach((element, i) => {
					element.setAttribute('delay', (50 * (i % 4 + 1)) + '')
					observerRecent.observe(element)
				})
			}
			setTimeout(() => {
				addAnimation()
			}, 100)
			this.recentData = data
			this.loading.recent = false
		},
	}

	setEvents() {
		this.loading.recent = true
		this.dataMethods.get('recent', this.variables.recent, (data: any) => {
			this.setPageData.recent(data)
		})
	}

	ngOnInit(): void {
		this.sharedView.changeState({
			method: 'setNavButton',
			params: ['recent']
		})
		this.setEvents()
	}

}

<div class="w-full min-h-full relative">
    <div *ngIf="modal" class="a-center h-full z-[4] bg-gray-900 bg-opacity-25 w-full fixed top-0 left-0">
        <div class="bg-slate-200 rounded-lg w-[350px]">
            <div class="p-5">
                <h1 class="text-2xl">Enter Page No.</h1>
            </div>
            <hr class="border-slate-400" />
            <div class="p-5">
                <input class="bg-transparent rounded-sm h-8 text-slate-800 px-2" type="number" placeholder="Page no."
                    (input)="pageNoOnChange($event)" />
            </div>
            <hr class="border-slate-400" />
            <div class="p-5 flex justify-end">
                <button (click)="hideModal()"
                    class="btn mr-2 py-2 pr-3 pl-2 text-[#dc3545] hover:bg-[#dc3545] hover:text-slate-200 border rounded-lg border-[#dc3545] flex">
                    <div class="a-center">
                        <ng-icon class="text-lg mr-1" name="heroArrowRightOnRectangleMini"></ng-icon>
                    </div>
                    <div class="a-center">
                        <span class="text-[14px] mt-[0.5px] font-semibold">Close</span>
                    </div>
                </button>
                <button (click)="submitPage()"
                    class="btn py-2 pr-3 pl-2 text-[#28a745] hover:bg-[#28a745] hover:text-slate-200 border rounded-lg border-[#28a745] flex">
                    <div class="a-center">
                        <ng-icon class="text-lg mr-1" name="heroArrowRightOnRectangleMini"></ng-icon>
                    </div>
                    <div class="a-center">
                        <span class="text-[14px] mt-[0.5px] font-semibold">Submit</span>
                    </div>
                </button>
            </div>
        </div>
    </div>
    <section class="container mx-auto">
        <div class="lg:m-10 lg:mt-10 mt-5 m-3">
            <div class="flex justify-between mb-2">
                <div class="flex">
                    <div class="a-center">
                        <ng-icon class="text-sgreen text-[25px] mr-1" name="heroNewspaper"></ng-icon>
                    </div>
                    <div class="a-center font-semibold">
                        <span class="text-slate-200 text-sm side-heading">Recently <span class="text-sgreen">Released</span></span>
                    </div>
                </div>
            </div>
            <div class="recent-container w-full overflow-x-scroll relative min-h-[600px]">
                <app-loader *ngIf="loading.recent"></app-loader>
                <div class="recent grid lg:grid-cols-4 md:grid-cols-3 sm:grid-cols-3 grid-cols-2 relative">
                    <div (click)="goToWatch(
                            item.media.id,
                            item.media.title.romaji ||
                            item.media.title.english ||
                            item.media.title.userPreferred ||
                            item.media.title.native,
                            item.episode
                        )" *ngFor="let item of recentData; index as i" class="cursor-pointer hidden-recent-card w-full p-2">
                        <div class="recent-card relative p-2 rounded-lg"
                            style="background-image: url({{item.media.coverImage.extraLarge}});">
                            <div
                                class="rounded-sm bg-[#5de4b5] absolute top-2 left-2 bg-opacity-80 px-2 text-[15px] font-[550]">
                                {{item.media.format.replaceAll('_', ' ')}}</div>
                            <div
                                class="rounded-sm absolute bottom-2 right-2 bg-black bg-opacity-60 text-slate-200 px-2 text-[15px] font-[550]">
                                {{item.media.duration || 23}}:00</div>
                        </div>
                        <h1 class="text-sm pt-2 flex justify-between text-slate-200">
                            <span>Episode:</span>
                            <span>{{item.episode}}</span>
                        </h1>
                        <h1 class="text-sm pt-0 flex justify-between text-slate-200">
                            <span><span class="lg:inline-flex md:inline-flex hidden">Episode</span> Aired on:</span>
                            <span>{{date(item.airingAt)}}</span>
                        </h1>
                        <h1 class="text-sm pt-1 font-semibold text-sgreen">
                            {{
                            item.media.title.userPreferred ||
                            item.media.title.english ||
                            item.media.title.romaji ||
                            item.media.title.native
                            }}
                        </h1>
                    </div>
                </div>
            </div>
            <div class="flex justify-center py-16">
                <div (click)="prevPage()"
                    class="a-center px-2 shadow-xl cursor-pointer hover:scale-110 rounded-sm mx-1 bg-sgreen">
                    <ng-icon class="text-lg font-normal" name="heroChevronLeft"></ng-icon>
                </div>
                <div (click)="showModal()"
                    class="a-center bg-slate-200 rounded-sm h-8 px-3 cursor-pointer hover:scale-110">
                    <span>{{variables.recent.page}}</span>
                </div>
                <div (click)="nextPage()"
                    class="a-center px-2 shadow-xl cursor-pointer hover:scale-110 rounded-sm mx-1 bg-sgreen">
                    <ng-icon class="text-lg font-normal" name="heroChevronRight"></ng-icon>
                </div>
            </div>
        </div>
    </section>
    <app-footer></app-footer>
</div>
