// frontend/src/app/pages/signup/signup.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { BackendService } from 'src/app/services/backend/backend.service';
import { SharedviewService } from 'src/app/services/sharedview/sharedview.service';

@Component({
	selector: 'app-signup',
	templateUrl: './signup.component.html',
	styleUrls: ['./signup.component.css']
})
export class SignupComponent {

	constructor(
		private router: Router,
		private server: BackendService,
		private sharedView: SharedviewService
	) { }

	ngOnInit(): void {
		this.sharedView.changeState({
			method: 'setNavButton',
			params: ['signup']
		})
	}

	loading: Boolean = false

	username: string = ''
	usermail: string = ''
	passwd: string = ''
	cpasswd: string = ''
	errors: any = {
		username: '',
		usermail: '',
		passwd: '',
		cpasswd: '',
		message: '',
	}

	validate(param: string) {
		let flag = true
		if (param === 'username' || param === 'all') {
			if (this.username === '') {
				this.errors.username = ''
			} else if (3 > this.username.length || this.username.length > 30) {
				this.errors.username = 'Name must be of size 3 to 30 characters'
				flag = false
			} else {
				this.errors.username = ''
			}
		}
		if (param === 'usermail' || param === 'all') {
			if (this.usermail === '') {
				this.errors.usermail = ''
			} else if (!/^[a-zA-Z0-9\.]{1,64}@[a-zA-Z0-9]{3,10}.com$/.test(this.usermail)) {
				this.errors.usermail = 'Unknown Email Format'
				flag = false
			} else {
				this.errors.usermail = ''
			}
		}
		if (param === 'passwd' || param === 'all') {
			if (this.passwd === '') {
				this.errors.passwd = ''
			} else if (this.passwd.length < 8) {
				this.errors.passwd = 'Contains atleast 8 chars'
				flag = false
			} else {
				this.errors.passwd = ''
			}
		}
		if (param === 'cpasswd' || param === 'all') {
			if (this.cpasswd === '') {
				this.errors.cpasswd = ''
			} else if (this.passwd !== this.cpasswd) {
				this.errors.cpasswd = 'Password didn\'t match'
				flag = false
			} else {
				this.errors.cpasswd = ''
			}
		}
		return flag
	}

	goToRoute(path: string): void {
		this.router.navigateByUrl(path)
	}

	submitForm(formData: any): void {
		if (!this.validate('all')) {
			return
		}
		this.loading = true
		this.server.post('/api/user/register', formData).subscribe((userData: any) => {
			this.loading = false
			if (userData.error) {
				this.errors.message = userData.error
				setTimeout(() => {
					this.errors.message = ''
				}, 5000)
				return
			}
			this.router.navigateByUrl('/login')
		})
	}

}

<div class="w-full h-full overflow-y-hidden a-center relative">
    <app-loader *ngIf="loading"></app-loader>
    <div class="z-[2] lg:w-4/12 md:w-6/12 w-10/12 lg:mb-0 md:mb-0 mb-24">
        <form #signUpForm="ngForm" (ngSubmit)="submitForm(signUpForm.value)">
            <div class="signup-container w-full rounded-lg bg-[#06151a] lg:p-10 md:p-10 p-5">
                <div class="mt-2">
                    <label for="username" class="block mb-2 text-md font-medium text-slate-200">Username</label>
                    <input type="text" name="username" [(ngModel)]="username" (input)="validate('username')"
                        id="username" placeholder="Enter your Name"
                        class="font-normal block w-full p-2 py-1 border rounded-sm text-md focus:ring-teal-500 focus:border-teal-500 bg-gray-700 border-gray-600 placeholder-gray-400 text-slate-200">
                    <span *ngIf="errors.username !== ''" class="text-red-300">{{errors.username}}</span>
                </div>
                <div class="mt-2">
                    <label for="usermail" class="block mb-2 text-md font-medium text-slate-200">User Mail</label>
                    <input type="email" name="usermail" [(ngModel)]="usermail" (input)="validate('usermail')"
                        id="usermail" placeholder="Enter your mail address"
                        class="font-normal block w-full p-2 py-1 border rounded-sm text-md focus:ring-teal-500 focus:border-teal-500 bg-gray-700 border-gray-600 placeholder-gray-400 text-slate-200">
                    <span *ngIf="errors.usermail !== ''" class="text-red-300">{{errors.usermail}}</span>
                </div>
                <div class="lg:flex md:flex block justify-between">
                    <div class="mt-2 lg:w-1/2 md:w-1/2 w-full">
                        <label for="passwd" class="block mb-2 text-md font-medium text-slate-200">Password</label>
                        <input type="password" name="passwd" [(ngModel)]="passwd" (input)="validate('passwd')"
                            id="passwd" placeholder="Enter your password"
                            class="font-normal block w-full p-2 py-1 border rounded-sm text-md focus:ring-teal-500 focus:border-teal-500 bg-gray-700 border-gray-600 placeholder-gray-400 text-slate-200">
                        <span *ngIf="errors.passwd !== ''" class="text-red-300">{{errors.passwd}}</span>
                    </div>
                    <div class="px-1"></div>
                    <div class="mt-2 lg:w-1/2 md:w-1/2 w-full">
                        <label for="cpasswd" class="block mb-2 text-md font-medium text-slate-200">Confirm
                            Password</label>
                        <input type="password" name="cpasswd" [(ngModel)]="cpasswd" (input)="validate('cpasswd')"
                            id="cpasswd" placeholder="Confirm your password"
                            class="font-normal block w-full p-2 py-1 border rounded-sm text-md focus:ring-teal-500 focus:border-teal-500 bg-gray-700 border-gray-600 placeholder-gray-400 text-slate-200">
                        <span *ngIf="errors.cpasswd !== ''" class="text-red-300">{{errors.cpasswd}}</span>
                    </div>
                </div>
                <span *ngIf="errors.message !== ''" class="text-red-300">{{errors.message}}</span>
                <div class="mt-8 flex justify-between">
                    <div class="a-center">
                        <span (click)="goToRoute('/login')" class="cursor-pointer text-sm text-sgreen">Already have an
                            account?</span>
                    </div>
                    <div>
                        <button type="submit"
                            class="btn py-2 pr-3 pl-2 text-sgreen hover:bg-sgreen hover:text-slate-800 border rounded-lg border-[#9fe6cd] flex">
                            <div class="a-center">
                                <ng-icon class="text-lg mr-1" name="heroArrowRightOnRectangleMini"></ng-icon>
                            </div>
                            <div class="a-center">
                                <span class="text-[14px] font-semibold">SignUp</span>
                            </div>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <ul class="bg-bubbles">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    </ul>
</div>

// frontend/src/Pages/Auth/SignUp/index.jsx
import AuthLayout from "/src/layouts/AuthLayout"
import { VscEye, VscEyeClosed } from "react-icons/vsc"
import { useEffect, useState } from "react"
import { MdAlternateEmail } from "react-icons/md"
import { FaShieldAlt } from "react-icons/fa"
import Logo from "/src/components/Logo"
import { motion } from "framer-motion"
import { Link } from "react-router-dom"
import { LuShieldCheck } from "react-icons/lu"
import { PiUserCircleDuotone } from "react-icons/pi"
import { FaRegUser } from "react-icons/fa"
import Loading from "/src/components/Button/Loading"
import backend from "/src/services/backend"
import { useNavigate } from "react-router-dom"

const SignUp = () => {
  const navigate = useNavigate()
  const [showPasswd, setShowPasswd] = useState(false)
  const [form, setForm] = useState({
    username: '',
    usermail: '',
    passwd: '',
    cpasswd: '',
  })
  const [error, setError] = useState({})
  const [signUpError, setSignUpError] = useState(null)
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    let interval = null
    if (signUpError) {
      interval = setTimeout(() => {
        setSignUpError(null)
      }, 5000)
    }
    return () => {
      clearTimeout(interval)
    }
  }, [signUpError])

  const handleChange = (event) => {
    const data = { ...form, [event.target.name]: event.target.value }
    setForm(data)
    validate(event.target.name, data)
  }
  const handleShowPasswd = () => {
    setShowPasswd(!showPasswd)
  }
  const handleSubmit = (event, { username, usermail, passwd, cpasswd }) => {
    event.preventDefault()
    if (!validate('all', { username, usermail, passwd, cpasswd })) {
      return
    }
    const body = { username, usermail, passwd, cpasswd }
    setLoading(true)
    backend.post('/api/user/register', body)
      .then(({ data }) => {
        if (data.error) {
          setSignUpError(data.error)
          return
        }
        navigate('/login')
      })
      .catch(error => {
        setSignUpError('Something went wrong')
        console.log(error)
      })
      .finally(() => {
        setLoading(false)
      })
  }

  const validate = (param, { username, usermail, passwd, cpasswd }) => {
    let flag = true
    if (param === 'username' || param === 'all') {
      if (username === '') {
        setError({ ...error, username: undefined })
        flag = false
      } else if (3 > username.length || username.length > 30) {
        setError({ ...error, username: 'Name must be of size 3 to 30 characters' })
        flag = false
      } else {
        setError({ ...error, username: undefined })
      }
    }
    if (param === 'usermail' || param === 'all') {
      if (usermail === '') {
        setError({ ...error, usermail: undefined })
        flag = false
      } else if (!/^[a-zA-Z0-9_.]{1,64}@[a-zA-Z0-9]{3,10}.com$/.test(usermail)) {
        setError({ ...error, usermail: 'Unknown Email Format' })
        flag = false
      } else {
        setError({ ...error, usermail: undefined })
      }
    }
    if (param === 'passwd' || param === 'all') {
      if (passwd === '') {
        setError({ ...error, passwd: undefined })
        flag = false
      } else if (passwd.length < 8) {
        setError({ ...error, passwd: 'Contains atleast 8 chars' })
        flag = false
      } else {
        setError({ ...error, passwd: undefined })
      }
    }
    if (param === 'cpasswd' || param === 'all') {
      if (cpasswd === '') {
        setError({ ...error, cpasswd: undefined })
        flag = false
      } else if (passwd !== cpasswd) {
        setError({ ...error, cpasswd: 'Password didn\'t match' })
        flag = false
      } else {
        setError({ ...error, cpasswd: undefined })
      }
    }
    return flag
  }

  return (
    <AuthLayout>
      <div className="w-full h-full a-center p-5 pb-[60px]">
        <div className="w-full md:w-[360px] glass glass hard v-center">
          <form
            className="w-full h-full"
            onSubmit={(e) => handleSubmit(e, form)}
          >
            <div className="h-[60px] flex justify-start p-5 pt-8">
              <Logo />
            </div>
            <div className="p-5 pt-3 w-full">
              <div className="relative w-full">
                <div className="absolute h-8 left-0 px-3 a-center">
                  <FaRegUser className="text-gray-400" />
                </div>
                <input
                  type="text"
                  value={form.username}
                  name="username"
                  onChange={handleChange}
                  className="h-8 w-full md:w-[300px] bg-transparent py-2 px-10 text-gray-200
                  rounded-lg ring-2 ring-teal-400 focus:ring-2 focus:ring-teal-300
                  tracking-wide text-sm"
                  placeholder="Enter Username"
                />
              </div>
              {
                error.username && <span className="-mb-5 text-red-300 text-xs">{error.username}</span>
              }
            </div>
            <div className="p-5 pt-0 w-full">
              <div className="relative w-full">
                <div className="absolute h-8 left-0 px-3 a-center">
                  <MdAlternateEmail className="text-gray-400" />
                </div>
                <input
                  type="email"
                  value={form.usermail}
                  name="usermail"
                  onChange={handleChange}
                  className="h-8 w-full md:w-[300px] bg-transparent py-2 px-10 text-gray-200
                  rounded-lg ring-2 ring-teal-400 focus:ring-2 focus:ring-teal-300
                  tracking-wide text-sm"
                  placeholder="Enter Email"
                />
              </div>
              {
                error.usermail && <span className="-mb-5 text-red-300 text-xs">{error.usermail}</span>
              }
            </div>
            <div className="p-5 pt-0 w-full">
              <div className="relative w-full">
                <div className="absolute h-8 left-0 px-3 a-center">
                  <FaShieldAlt className="text-gray-400" />
                </div>
                <input
                  type={showPasswd ? "text" : "password"}
                  value={form.passwd}
                  name="passwd"
                  onChange={handleChange}
                  className="h-8 w-full md:w-[300px] bg-transparent py-2 px-10 text-gray-200
                  rounded-lg ring-2 ring-teal-400 focus:ring-2 focus:ring-teal-300
                  tracking-wide text-sm"
                  placeholder="Enter Password"
                />
                <div className="absolute top-0 h-8 right-0 px-3 a-center">
                  <button onClick={handleShowPasswd} type="button">
                    {
                      showPasswd
                        ? <VscEye className="text-gray-200" />
                        : <VscEyeClosed className="text-gray-200" />
                    }
                  </button>
                </div>
              </div>
              {
                error.passwd && <span className="-mb-5 text-red-300 text-xs">{error.passwd}</span>
              }
            </div>
            <div className="p-5 pt-0 w-full">
              <div className="relative w-full">
                <div className="absolute h-8 left-0 px-3 a-center">
                  <LuShieldCheck className="text-gray-400" />
                </div>
                <input
                  type="password"
                  value={form.cpasswd}
                  name="cpasswd"
                  onChange={handleChange}
                  className="h-8 w-full md:w-[300px] bg-transparent py-2 px-10 text-gray-200
                  rounded-lg ring-2 ring-teal-400 focus:ring-2 focus:ring-teal-300
                  tracking-wide text-sm"
                  placeholder="Confirm Password"
                />
              </div>
              {
                error.cpasswd && <span className="-mb-5 text-red-300 text-xs">{error.cpasswd}</span>
              }
              {
                signUpError && <span className="-mb-5 text-red-300 text-xs">{signUpError}</span>
              }
            </div>
            <div className="p-5 pt-0 pb-3 flex justify-between">
              <div className="pr-3 flex v-center">
                <Link to="/login">
                  <p className="text-sgreen text-xs cursor-pointer">Already have an account?</p>
                </Link>
              </div>
              {
                loading
                  ? <Loading>
                    <span>Registering...</span>
                  </Loading>
                  : <motion.div
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                  >
                    <button
                      type="submit"
                      className="inline-flex items-center px-4 py-2
                  rounded-md font-semibold text-xs uppercase tracking-widest shadow-sm
                  transition ease-in-out duration-150
                  text-[#111827] bg-[#cbd5e1cc]
                  hover:bg-[#e5e7ebee]
                  disabled:opacity-25"
                    >
                      <div className="flex justify-center">
                        <div className="a-center mr-1">
                          <span className="text-xs inline-flex">SignUp</span>
                        </div>
                        <div className="a-center">
                          <PiUserCircleDuotone className="text-lg" />
                        </div>
                      </div>
                    </button >
                  </motion.div>
              }
            </div>
          </form>
        </div>
      </div>
    </AuthLayout>
  )
}

export default SignUp
