// frontend/src/app/home/home.component.ts
import { Component } from '@angular/core'

@Component({
	selector: 'app-home',
	templateUrl: './home.component.html',
	styleUrls: ['./home.component.css']
})

export class HomeComponent {

	constructor() { }

	ngOnInit(): void { }

}

<div class="w-full h-screen a-center">
    <h1 class="text-2xl flex font-semibold text-slate-200">
        <div class="a-center mr-1">
            <ng-icon name="heroBolt"></ng-icon>
        </div>
        <div class="a-center">
            <span>MixAnime!</span>
        </div>
    </h1>
</div>

// src/Pages/Home.jsx
import MainLayout from "../layouts/MainLayout"

const Home = () => {
  return (
    <MainLayout>
      <h1 className="h-screen a-center font-semibold text-slate-200">Home Page!</h1>
      <h1 className="h-screen a-center font-semibold text-slate-200">Home Page!</h1>
    </MainLayout>
  )
}

export default Home
