// frontend/src/app/pages/schedule/schedule.component.ts
import { Component } from '@angular/core';
import { SharedviewService } from 'src/app/services/sharedview/sharedview.service';

@Component({
	selector: 'app-schedule',
	templateUrl: './schedule.component.html',
	styleUrls: ['./schedule.component.css']
})
export class ScheduleComponent {

	constructor(private sharedView: SharedviewService) { }

	ngOnInit(): void {
		this.sharedView.changeState({
			method: 'setNavButton',
			params: ['schedule']
		})
		this.sharedView.changeState({
			method: 'checkLogin',
			params: []
		})
	}

}

<div class="w-full min-h-full lg:p-10 md:p-10 pt-0 p-5" relative>
    <div *ngIf="loading.schedule" class="h-[800px] relative">
        <app-loader></app-loader>
    </div>
    <div *ngIf="!loading.schedule" class="py-5 flex flex-col space-y-3 w-full">
        <div class="heading pb-5">
            <span class="side-heading text-slate-200">
                Weekly <span class="text-sgreen">Schedule</span>
            </span>
        </div>
        <div class="w-full" *ngFor="let day of range">
            <div class="flex justify-between p-2">
                <div class="a-center">
                    <span class="text-lg font-semibold text-slate-200">{{scheduleHead[day]}}</span>
                </div>
                <div class="a-center">
                    <button *ngIf="scheduleData[day] === null" (click)="showEvent(day)"
                        class="login btn py-2 pr-3 pl-2 text-sgreen hover:bg-sgreen hover:text-slate-800 border rounded-lg border-[#9fe6cd] flex">
                        <div class="a-center">
                            <ng-icon class="text-lg mr-1" name="tablerCalendarDown"></ng-icon>
                        </div>
                        <div class="a-center">
                            <span class="text-[14px] font-semibold">View</span>
                        </div>
                    </button>
                    <button *ngIf="scheduleData[day] !== null" (click)="hideEvent(day)"
                        class="login btn py-2 pr-3 pl-2 text-sgreen hover:bg-sgreen hover:text-slate-800 border rounded-lg border-[#9fe6cd] flex">
                        <div class="a-center">
                            <ng-icon class="text-lg mr-1" name="tablerCalendarUp"></ng-icon>
                        </div>
                        <div class="a-center">
                            <span class="text-[14px] font-semibold">Hide</span>
                        </div>
                    </button>
                </div>
            </div>
            <div class="schedule-{{day}} hide-day-schedule hidden">
                <ol class="w-full bg-[#011116] rounded-2xl flex flex-row overflow-x-scroll p-5">
                    <li *ngFor="let item of scheduleData[day]" class="relative mb-6 sm:mb-0">
                        <div (click)="goToDetails(item.media.id)" class="cursor-pointer min-w-[300px] flex items-center">
                            <div
                                class="z-10 flex items-center justify-center w-6 h-6 rounded-full ring-[5px] bg-sgreen ring-slate-700 shrink-0">
                                <ng-icon class="text-md" name="heroCalendarDaysSolid"></ng-icon>
                            </div>
                            <div class="w-full h-[3px] bg-slate-700"></div>
                        </div>
                        <div class="mt-3 h-fit pr-8">
                            <h3 class="text-md truncate cursor-pointer font-semibold text-slate-200 pb-1">
                                {{truncate(item?.media?.title?.english || item?.media?.title?.romaji, 40)}}</h3>
                            <time class="block mb-2 text-sm font-normal leading-none text-slate-300 pb-2">Releases on
                                <span class="text-sgreen">{{date(item?.airingAt)}}</span></time>
                            <div class="w-full flex justify-between mb-2">
                                <img (click)="goToDetails(item.media.id)" class="cursor-pointer w-[150px] aspect-[3/4]" src="{{item?.media?.coverImage.extraLarge}}" alt="">
                                <div>
                                    <span class="block pt-1 text-xs text-slate-200">Format: <span
                                            class="text-sgreen">{{(item?.media?.format).split('_').join(' ')}}</span></span>
                                    <span class="block pt-1 text-xs text-slate-200">Duration: <span
                                            class="text-sgreen">{{(item?.media?.duration || 23)}} min</span></span>
                                    <span class="block pt-1 text-xs text-slate-200">Country: <span
                                            class="text-sgreen">{{item?.media?.countryOfOrigin}}</span></span>
                                    <span class="block pt-1 text-xs text-slate-200">Episode: <span
                                            class="text-sgreen">{{item?.episode}}</span></span>
                                </div>
                            </div>
                            <p class="text-xs font-normal text-slate-300"
                                [innerHTML]="truncate(item?.media?.description, 200)"></p>
                        </div>
                    </li>
                    <li class="relative mb-6 sm:mb-0">
                        <div>
                            <div
                                class="z-10 flex items-center justify-center w-6 h-6 rounded-full ring-[5px] bg-sgreen ring-slate-700 shrink-0">
                                <ng-icon class="text-md" name="heroCalendarDaysSolid"></ng-icon>
                            </div>
                        </div>
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
<app-footer></app-footer>

// frontend/src/components/Card/Schedule.jsx
import { PropTypes } from "prop-types"
import { getDate, truncate, getQueryParams } from "/src/services/untils"
import { HiCalendarDays } from "react-icons/hi2"
import { Link } from "react-router-dom"
import { motion } from "framer-motion"


const Schedule = ({ data }) => {
  const id = data.media.id
  const date = getDate(data.airingAt)
  const title = data.media.title.english || data.media.title.romaji
  const image = data.media.coverImage.extraLarge
  const format = data.media.format?.split('_')?.join(' ') || 'NA'
  const duration = data.media.duration || 23
  const country = data.media.countryOfOrigin
  const episode = data.episode

  return (
    <div className="relative py-5 mb-6 sm:mb-0" >
      <div className="cursor-pointer min-w-[300px] flex items-center" >
        <div
          className="z-10 flex items-center justify-center w-6 h-6 rounded-full ring-[5px] bg-sgreen ring-[#ffffff44] shrink-0">
          <HiCalendarDays className="text-md" />
        </div>
        <div className="w-full h-[3px] bg-[#ffffff44] mx-[5px]"></div>
      </div >
      <div className="mt-3 h-fit pr-8">
        <h3 className="text-sm truncate cursor-pointer font-semibold text-slate-200 pb-1">
          {truncate(title, 40)}</h3>
        <time className="block mb-2 text-[13px] font-normal leading-none text-slate-300 pb-2">
          Releases on <span className="text-sgreen">{date}</span>
        </time>
        <div className="w-full flex justify-between mb-2">
          <motion.div
            className="w-[150px] aspect-[3/4]"
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.95 }}
          >
            <Link
              to={{
                pathname: '/details',
                search: getQueryParams({ id })
              }}
            >
              <img
                className="cursor-pointer w-full h-full rounded-lg"
                src={image}
                alt=""
              />
            </Link>
          </motion.div>
          <div>
            <span className="block pt-1 text-xs text-slate-200">
              Format: <span className="text-sgreen">{format}</span>
            </span>
            <span className="block pt-1 text-xs text-slate-200">
              Duration: <span className="text-sgreen">{duration} min</span>
            </span>
            <span className="block pt-1 text-xs text-slate-200">
              Country: <span className="text-sgreen">{country}</span>
            </span>
            <span className="block pt-1 text-xs text-slate-200">
              Episode: <span className="text-sgreen">{episode}</span>
            </span>
          </div>
        </div>
        <p className="text-xs font-normal text-slate-300"
          type="desc"
          dangerouslySetInnerHTML={{ __html: truncate(data.media.description, 200) }}
        ></p>
      </div>
    </div>
  )
}

Schedule.propTypes = {
  data: PropTypes.any
}

export default Schedule
